// Generated by gencpp from file dronesentinelaa/AddTwoInts.msg
// DO NOT EDIT!


#ifndef DRONESENTINELAA_MESSAGE_ADDTWOINTS_H
#define DRONESENTINELAA_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <dronesentinelaa/AddTwoIntsRequest.h>
#include <dronesentinelaa/AddTwoIntsResponse.h>


namespace dronesentinelaa
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace dronesentinelaa


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dronesentinelaa::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::dronesentinelaa::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::dronesentinelaa::AddTwoInts > {
  static const char* value()
  {
    return "dronesentinelaa/AddTwoInts";
  }

  static const char* value(const ::dronesentinelaa::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::dronesentinelaa::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::dronesentinelaa::AddTwoInts >
template<>
struct MD5Sum< ::dronesentinelaa::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dronesentinelaa::AddTwoInts >::value();
  }
  static const char* value(const ::dronesentinelaa::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dronesentinelaa::AddTwoIntsRequest> should match
// service_traits::DataType< ::dronesentinelaa::AddTwoInts >
template<>
struct DataType< ::dronesentinelaa::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::dronesentinelaa::AddTwoInts >::value();
  }
  static const char* value(const ::dronesentinelaa::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dronesentinelaa::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::dronesentinelaa::AddTwoInts >
template<>
struct MD5Sum< ::dronesentinelaa::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dronesentinelaa::AddTwoInts >::value();
  }
  static const char* value(const ::dronesentinelaa::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dronesentinelaa::AddTwoIntsResponse> should match
// service_traits::DataType< ::dronesentinelaa::AddTwoInts >
template<>
struct DataType< ::dronesentinelaa::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::dronesentinelaa::AddTwoInts >::value();
  }
  static const char* value(const ::dronesentinelaa::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONESENTINELAA_MESSAGE_ADDTWOINTS_H
